CREATE TABLE IF NOT EXISTS `goat_stats` (
    id                  INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    playerid            VARCHAR(128) NOT NULL,
    pointspergame       FLOAT,
    reboundspergame     FLOAT,
    assistspergame      FLOAT,
    stealspergame       FLOAT,
    blockspergame       FLOAT,
    fgpercentage        FLOAT,
    threeptpercentage   FLOAT,
    ftpercentage        FLOAT,
    turnoverspergame    FLOAT,
    per                 FLOAT,
    ows                 FLOAT,
    dws                 FLOAT,
    ws                  FLOAT,
    obpm                FLOAT,
    dbpm                FLOAT,
    bpm                 FLOAT,
    vorp                FLOAT,
    offrtg              FLOAT,
    defrtg              FLOAT,
    totalpoints         INT,
    totalrebounds       INT,
    totalassists        INT,
    totalsteals         INT,
    totalblocks         INT,
    isplayoffs          BOOLEAN default false,
    isactive            BOOLEAN default false,
    position            VARCHAR(5),
    FOREIGN KEY(playerid) REFERENCES `goat_players`(playerid)
);