CREATE TABLE IF NOT EXISTS `players` (
  id                INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  playerid          VARCHAR(128) NOT NULL,
  name              VARCHAR(128) NOT NULL,
  teamabbr          VARCHAR(5)NOT NULL,
  college           VARCHAR(128),
  height            VARCHAR(5) NOT NULL,
  weight            VARCHAR(5) NOT NULL,
  age               INT NOT NULL,
  gamesplayed       INT,
  minutespergame    FLOAT,
  pointspergame     FLOAT,
  reboundspergame   FLOAT,
  assistspergame    FLOAT,
  stealspergame     FLOAT,
  fgpercentage      FLOAT,
  threeptpercentage FLOAT,
  ftpercentage      FLOAT,
  blockspergame     FLOAT,
  turnoverspergame  FLOAT,
  FOREIGN KEY(teamabbr) REFERENCES `teams`(teamabbr)
);