name: Sportsvoting-workflow
'on':
    push:
        branches:
            - master
        tags:
          - 'v*'
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            include:
              - dockerfile: ./Dockerfile
                image: emirhamidovic/sportsvoting-api
                context: .
              - dockerfile: ./frontend/Dockerfile
                image: emirhamidovic/sportsvoting-frontend
                context: frontend
        steps:
            - name: Checkout-Repository
              uses: actions/checkout@v4

            - name: Get Version
              id: get_version
              uses: battila7/get-version-action@v2.2.1
            - run: echo ${{ steps.get_version.outputs.version }}
            - run: echo ${{ steps.get_version.outputs.version-without-v }}

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ matrix.image }}

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Push to Docker Hub
              uses: docker/build-push-action@v5
              with:
                context: ${{ matrix.context }}
                file: ${{ matrix.dockerfile }}
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                
